export const shoes = [
  {
    id: 1,
    name: "Skórzane botki damskie",
    price: 59.99,
    discountPrice: 30.1,
    discountNote: "Najniższa cena z 30 dni przed obniżką: 59,99zł",
    tags: [
      { type: "bestseller", text: "BESTSELLER" },
      { type: "sale", text: "PROMOCJA" },
    ],
    image: "https://picsum.photos/350/450?random=1",
  },
  {
    id: 2,
    name: "Trampki męskie klasyczne",
    price: 29.99,
    discountPrice: null,
    discountNote: null,
    tags: [{ type: "new", text: "NOWOŚĆ" }],
    image: "https://picsum.photos/350/450?random=2",
  },
  {
    id: 3,
    name: "Sportowe sneakersy damskie",
    price: 58.89,
    discountPrice: 43.32,
    discountNote: "Najniższa cena z 10 dni przed obniżką: 58,89zł",
    tags: [{ type: "sale", text: "PROMOCJA" }],
    image: "https://picsum.photos/350/450?random=3",
  },
  {
    id: 4,
    name: "Eleganckie półbuty męskie",
    price: 79.99,
    discountPrice: 69.99,
    discountNote: "Najniższa cena z 14 dni przed obniżką: 79,99zł",
    tags: [{ type: "sale", text: "PROMOCJA" }],
    image: "https://picsum.photos/350/450?random=4",
  },
  {
    id: 5,
    name: "Sandały skórzane damskie",
    price: 49.99,
    discountPrice: null,
    discountNote: null,
    tags: [{ type: "new", text: "NOWOŚĆ" }],
    image: "https://picsum.photos/350/450?random=5",
  },
  {
    id: 6,
    name: "Buty trekkingowe męskie",
    price: 120,
    discountPrice: 99,
    discountNote: "Najniższa cena z 7 dni przed obniżką: 120,00zł",
    tags: [
      { type: "new", text: "NOWOŚĆ" },
      { type: "sale", text: "PROMOCJA" },
    ],
    image: "https://picsum.photos/350/450?random=6",
  },
  {
    id: 7,
    name: "Klapki na koturnie damskie",
    price: 39.5,
    discountPrice: null,
    discountNote: null,
    tags: [{ type: "new", text: "NOWOŚĆ" }],
    image: "https://picsum.photos/350/450?random=7",
  },
  {
    id: 10,
    name: "Półbuty eleganckie z lakierowanej skóry",
    price: 89.99,
    discountPrice: null,
    discountNote: null,
    tags: [{ type: "bestseller", text: "BESTSELLER" }],
    image: "https://picsum.photos/350/450?random=10",
  },
  {
    id: 8,
    name: "Mokasyny męskie zamszowe",
    price: 65.49,
    discountPrice: 55.49,
    discountNote: "Najniższa cena z 14 dni przed obniżką: 65.49zł",
    tags: [
      { type: "sale", text: "PROMOCJA" },
      { type: "bestseller", text: "BESTSELLER" },
    ],
    image: "https://picsum.photos/350/450?random=8",
  },
  {
    id: 9,
    name: "Sneakersy dziecięce kolorowe",
    price: 45.99,
    discountPrice: null,
    discountNote: null,
    tags: [{ type: "bestseller", text: "BESTSELLER" }],
    image: "https://picsum.photos/350/450?random=9",
  },
  {
    id: 11,
    name: "Buty do biegania unisex",
    price: 74.5,
    discountPrice: null,
    discountNote: null,
    tags: [
      { type: "bestseller", text: "BESTSELLER" },
      { type: "new", text: "NOWOŚĆ" },
    ],
    image: "https://picsum.photos/350/450?random=11",
  },
];
